### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [107]:
import pandas as pd
import numpy as np

a = pd.Series([1, 2, 3, 4, 5]) 
b = np.array([[1,2,3], [4,5,6]])

def myfunction(array):
    if array.ndim != 1:
        return "¡¡¡Error, feed me a 1D array!!!"
    else:
        return array.describe()

print('Example with array A: \n', myfunction(a),'\n')

print('Example with array B: ', myfunction(b))

Example with array A: 
 count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64 

Example with array B:  ¡¡¡Error, feed me a 1D array!!!


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [121]:
import random


def quadr():
    N = random.randint(1,10)
    quadrat = np.random.randint(0,101,size=(N,N), )
    print(quadrat, '\n')
    return quadrat

print(quadr().shape)

[[ 29  74  94  10  28  66  69]
 [  0  77  34  18  86  29  55]
 [ 93  33  57  38 100  87  10]
 [ 35  53  45  77  64  69  43]
 [ 35  66  80  98  11  61  51]
 [ 61  72  35  34  73  89  10]
 [ 73  63  61  43   6  23  27]] 

(7, 7)


### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [110]:
def totals(array_2d):
    num_rows = len(array_2d)
    num_columns = len(array_2d[0])
    print(num_rows, ' ROWS:')
    for x in range(num_rows):
        print(f'Sum of row {x} equals {array_2d[x].sum()}')
    print(num_columns, ' COLUMNS:')
    for y in range(num_columns):    
        print(f'Sum of Column {y} equals {array_2d[:,y].sum()}')
    print('-----------------')   
b = np.random.random((2,random.randint(0,20)))
print(b, '\n')
print(f'Array has {b.ndim} dimensions.\n')
print(totals(b))
    

[[0.60734845 0.88230805 0.4835254  0.91512178 0.67136289 0.79256001
  0.87230688 0.67286574 0.47751752 0.42838482 0.42992519 0.14756597]
 [0.64575292 0.6999596  0.92468428 0.64966005 0.01385736 0.64593451
  0.48366232 0.47595834 0.24670357 0.43284815 0.48126291 0.16446093]] 

Array has 2 dimensions.

2  ROWS:
Sum of row 0 equals 7.380792708165989
Sum of row 1 equals 5.864744916792494
12  COLUMNS:
Sum of Column 0 equals 1.2531013663031718
Sum of Column 1 equals 1.5822676497225416
Sum of Column 2 equals 1.4082096856659616
Sum of Column 3 equals 1.5647818326765852
Sum of Column 4 equals 0.6852202435417079
Sum of Column 5 equals 1.438494519097115
Sum of Column 6 equals 1.3559691962072569
Sum of Column 7 equals 1.1488240786594313
Sum of Column 8 equals 0.7242210895605139
Sum of Column 9 equals 0.8612329663314315
Sum of Column 10 equals 0.911188095979576
Sum of Column 11 equals 0.3120269012131889
-----------------
None


### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [133]:
#Si tenim una taula de n mostres amb 2 variables x e y
taula = np.random.randint(1,40,size=(2,10))
h = taula.view()
n = len(taula[:1])
print(h, '\n')

#treiem la mitja de cada variable per poder fer les variances 
media_x = taula[:1].mean()
media_y = taula[1:].mean()

#calculem primer la variancia de x e y
#que sera la desviacio estandar de cada variable elevada al cuadrat
#o pitjor(el sumatori de les diferencies entre cada mostra i la 
#seva mitja elevats al cuadrat dividit pel nombre total de mostres)
var_x = 0
for x in taula[:1] :
    var_x += ((x - media_x)**2)/n
print(var_x)
print(var_x/n)
#def coef_rel(x,y):
 #   var_x = x - x.mean
  #  var_y = 
#

[[ 5 39  2  5 20  8  4 18 12 31]
 [ 1 21 34 31 34 37 35 21  8 30]] 

[ 88.36 605.16 153.76  88.36  31.36  40.96 108.16  12.96   5.76 275.56]
[ 88.36 605.16 153.76  88.36  31.36  40.96 108.16  12.96   5.76 275.56]
